# config/node.yaml
default_node: node1

nodes:
  node1:
    name: 默认测速节点
    url: https://alist.elsworld.cn:8443/d/Temp/Diskgenius_Pro_x86_5.5.0.1488_cn.exe?sign=9gXPx3V8rLJnlUf5MIHfcDVJc2yIt34XCnuZPgZoCH8=:0
    
  node2:
    name: 备用测速节点
    url: https://dldir1v6.qq.com/qqfile/qq/QQNT/Windows/QQ_9.9.20_250724_x64_01.exe
    
  node3:
    name: 国际测速节点
    url: https://cdn.jsdelivr.net/gh/prometheus/prometheus@main/LICENSE